[package]
name = "matroska"
description = "Library for parsing Matroska (MKV) file metadata."
keywords = ["matroska", "mkv"]
version = "0.5.4"
authors = ["Brian Langenberger <bjl@usa.net>"]
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/matroska/"
homepage = "https://github.com/tuffy/matroska"
repository = "https://github.com/tuffy/matroska"
edition = "2018"

[dependencies]
bitstream-io = "0.8"
chrono = "0.4"
phf = { version = "0.8", features = ["macros"] }
